# -*- coding: utf-8 -*-
"""Copy of FINAL Essay NLP Project - Naman and Jack

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xH7z2CMOPA5ONLDiBnrKyTLvcV8EVWVN
"""

!pip install nltk pandas numpy matplotlib seaborn scikit-learn

# Essay NLP Project
# Jack He and Naman Kumar

# Libraries
import pandas as pd
import numpy as np
import re
import string
import matplotlib.pyplot as plt
import seaborn as sns

# NLP / ML Libraries
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (
    accuracy_score,
    classification_report,
    confusion_matrix,
    precision_score,
)

# Load, preprocess dataset
data_path = "classexampleOpenAI.csv"
df = pd.read_csv(data_path)

# Drop rows with missing text or label
df.dropna(subset=["Text", "Course"], inplace=True)

# Normalize label case (helps with duplicate labels)
df["Course"] = df["Course"].str.strip().str.title()

# Drop very rare classes (fewer than 2 samples)
label_counts = df["Course"].value_counts()
valid_labels = label_counts[label_counts >= 2].index
df = df[df["Course"].isin(valid_labels)]

# Show updated label distribution
label_counts = df["Course"].value_counts()

plt.figure(figsize=(10, 6))
sns.barplot(x=label_counts.index, y=label_counts.values, palette="viridis")
plt.title("Course Label Distribution (Min 2 Samples)")
plt.ylabel("Number of Essays")
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.show()

# Text Cleaning
STOPWORDS = set(stopwords.words("english"))

def clean_text(text: str) -> str:
    text = text.lower()
    text = re.sub(f"[{re.escape(string.punctuation)}]", " ", text)
    tokens = text.split()  # avoid nltk tokenizer to prevent errors
    tokens = [tok for tok in tokens if tok not in STOPWORDS and tok.isalpha()]
    return " ".join(tokens)

df["clean_text"] = df["Text"].astype(str).apply(clean_text)

# Vectorization
tfidf = TfidfVectorizer(ngram_range=(1, 2), max_features=5000)
X = tfidf.fit_transform(df["clean_text"])
y = df["Course"]

# Train/Test Split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)
print(f"\nTrain size: {X_train.shape[0]}, Test size: {X_test.shape[0]}")

# Model Training
clf = LogisticRegression(max_iter=1000, n_jobs=-1)
clf.fit(X_train, y_train)

# Evaluation
y_pred = clf.predict(X_test)
print(f"\nAccuracy: {accuracy_score(y_test, y_pred):.4f}\n")
print("Classification Report:\n")
print(classification_report(y_test, y_pred, zero_division=0))

# Precision scores per label
print("Precision Scores by Label:")
precision_per_label = precision_score(y_test, y_pred, average=None, labels=clf.classes_, zero_division=0)
for label, score in zip(clf.classes_, precision_per_label):
    print(f"{label}: {score:.4f}")

# Confusion Matrix
conf_mat = confusion_matrix(y_test, y_pred, labels=clf.classes_)
plt.figure(figsize=(10, 8))
sns.heatmap(conf_mat, annot=True, fmt="d", cmap="Blues", xticklabels=clf.classes_, yticklabels=clf.classes_)
plt.title("Confusion Matrix")
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.tight_layout()
plt.show()

# Top TF-IDF Features per Label
feature_names = tfidf.get_feature_names_out()
coef_df = pd.DataFrame(clf.coef_.T, index=feature_names, columns=clf.classes_)

for label in clf.classes_:
    print(f"\nTop 10 TF-IDF Features for '{label}':")
    print(coef_df[label].nlargest(10))

# Summary
print("\nSUMMARY:")
print("This model classifies essays based on text to predict the course label.")
print("- Labels with very few samples were dropped to avoid training issues.")
print("- Accuracy may be low due to overlapping vocabulary or small dataset.")
print("- TF-IDF reveals the most important keywords per course.")
print("- Improvements: more data, label merging, advanced models (e.g. BERT), or better preprocessing.")