# -*- coding: utf-8 -*-
"""Titanic.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OqHMQCeoiCn0YzyB6XAYaZQyFqOvehVk

##  Import and Load Data
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.preprocessing import LabelEncoder, StandardScaler, OneHotEncoder
from sklearn.impute import SimpleImputer
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.metrics import accuracy_score
from sklearn.feature_selection import mutual_info_classif
from sklearn.decomposition import PCA
from sklearn.cluster import KMeans

train = pd.read_csv('/content/drive/MyDrive/Advanced ML/titanictrain.csv')
test = pd.read_csv('/content/drive/MyDrive/Advanced ML/titanictest.csv')

"""## Data Exploration"""

df.head()

df.dtypes

df.columns

df.isna()
df.dtypes
df.isna().sum()

"""## ML"""

# Data overview
print("Training Data Shape:", train.shape)
print("Test Data Shape:", test.shape)

# Define target variable and features
y = train['Survived']
X = train.drop(['PassengerId', 'Survived', 'Name', 'Ticket', 'Cabin'], axis=1)
test_ids = test['PassengerId']
test = test.drop(['PassengerId', 'Name', 'Ticket', 'Cabin'], axis=1)

# Combine train and test for feature engineering
data = pd.concat([X, test], axis=0)

# Handle missing values
data['Age'] = data['Age'].fillna(data['Age'].median())
data['Fare'] = data['Fare'].fillna(data['Fare'].median())
data['Embarked'] = data['Embarked'].fillna(data['Embarked'].mode()[0])

# Data overview
print("Training Data Shape:", train.shape)
print("Test Data Shape:", test.shape)

# Define target variable and features
y = train['Survived']
X = train.drop(['PassengerId', 'Survived', 'Name', 'Ticket', 'Cabin'], axis=1)
test_ids = test['PassengerId']
test = test.drop(['PassengerId', 'Name', 'Ticket', 'Cabin'], axis=1)

# Combine train and test for feature engineering
data = pd.concat([X, test], axis=0)

# Handle missing values
data['Age'] = data['Age'].fillna(data['Age'].median())
data['Fare'] = data['Fare'].fillna(data['Fare'].median())
data['Embarked'] = data['Embarked'].fillna(data['Embarked'].mode()[0])

# Encode categorical variables using One-Hot Encoding
data = pd.get_dummies(data, columns=['Sex', 'Embarked'], drop_first=True)

# Create new feature: Family Size
data['FamilySize'] = data['SibSp'] + data['Parch'] + 1

# Create new feature: Is Alone
data['IsAlone'] = (data['FamilySize'] == 1).astype(int)

# Use k-means clustering to create a feature for fare segmentation
kmeans = KMeans(n_clusters=3, random_state=42, n_init=10)
data['FareCluster'] = kmeans.fit_predict(data[['Fare']])

# Apply Principal Component Analysis (PCA) for dimensionality reduction
scaler = StandardScaler()
data_scaled = scaler.fit_transform(data)
pca = PCA(n_components=5)
data_pca = pca.fit_transform(data_scaled)

pca_columns = [f'PCA_{i}' for i in range(5)]
data_pca_df = pd.DataFrame(data_pca, columns=pca_columns)

# Reset index for both DataFrames
data = data.reset_index(drop=True)
data_pca_df = data_pca_df.reset_index(drop=True)

# Concatenate with PCA features
data = pd.concat([data, data_pca_df], axis=1)

# Split the data back into train and test
X = data.iloc[:len(y), :]
X_test = data.iloc[len(y):, :]

# Train/test split
X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.2, random_state=42)

# Train Gradient Boosting Classifier (add more options)
gbc = GradientBoostingClassifier(random_state=42)
gbc_params = {
    'n_estimators': 200,
    'learning_rate': 0.05,
    'max_depth': 3,
}

grid_search = GridSearchCV(
    estimator=gbc,
    param_grid=gbc_params,
    scoring='accuracy',
    cv = X_val,
    verbose=1,
    n_jobs=-1
)

grid_search.fit(X_train, y_train)

# Best model
best_gbc = grid_search.best_estimator_
print("Best Parameters:", grid_search.best_params_)

# Model evaluation
y_pred_val = best_gbc.predict(X_val)
accuracy = accuracy_score(y_val, y_pred_val)
print(f"Validation Accuracy: {accuracy}")

# Predictions on test set
y_pred_test = best_gbc.predict(X_test)

# Prepare submission
submission = pd.DataFrame({
    'PassengerId': test_ids,
    'Survived': y_pred_test
})

# Save submission file
submission.to_csv('submission.csv', index=False)
print("Submission file has been successfully created!")

from google.colab import files
files.download("submission.csv")

from google.colab import drive
drive.mount('/content/drive')