# -*- coding: utf-8 -*-
"""House Prices ML

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cq9k4NaEnISxxQ7LS4gU2HiUu4p3cO0G
"""

# Import necessary libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.linear_model import Lasso
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.metrics import mean_squared_error

# Load the data
train = pd.read_csv('train.csv')
test = pd.read_csv('test.csv')

# Data overview
print("Training Data Shape:", train.shape)
print("Test Data Shape:", test.shape)

# Log-transform the target variable (SalePrice) to normalize it
train['SalePrice'] = np.log1p(train['SalePrice'])

# Define target variable and features
y = train['SalePrice']
X = train.drop(['Id', 'SalePrice'], axis=1)
test_ids = test['Id']
test = test.drop(['Id'], axis=1)

# Combine train and test for feature engineering
data = pd.concat([X, test], axis=0)

# Handling missing values (Fix for inplace warning)
for col in data.columns:
    if data[col].dtype == 'object':
        data.loc[:, col] = data[col].fillna('None')  # Fill categorical NaN with 'None'
    else:
        data.loc[:, col] = data[col].fillna(data[col].median())  # Fill numeric NaN with median

# Encode categorical variables
categorical_cols = data.select_dtypes(include=['object']).columns
label_encoders = {}
for col in categorical_cols:
    le = LabelEncoder()
    data.loc[:, col] = le.fit_transform(data[col])
    label_encoders[col] = le

# Scale numerical features
numerical_cols = data.select_dtypes(include=['int64', 'float64']).columns
scaler = StandardScaler()
data.loc[:, numerical_cols] = scaler.fit_transform(data[numerical_cols])

# Split the data back into train and test
X = data.iloc[:len(y), :]
X_test = data.iloc[len(y):, :]

# Train/test split
X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.2, random_state=42)

# Feature selection with LASSO (Fix ConvergenceWarning by increasing max_iter)
lasso = Lasso(alpha=0.01, max_iter=5000, random_state=42)
lasso.fit(X_train, y_train)
selected_features = X_train.columns[np.abs(lasso.coef_) > 1e-5]  # Keep only relevant features
X_train = X_train[selected_features]
X_val = X_val[selected_features]
X_test = X_test[selected_features]

# Gradient Boosting Regressor with fixed parameters to speed up training
gbr = GradientBoostingRegressor(random_state=42)
gbr_params = {
    'n_estimators': [200],  # Reduced to a single optimized value
    'learning_rate': [0.05],  # Optimal value found in tuning
    'max_depth': [5],  # Balanced depth for performance
}

grid_search = GridSearchCV(
    estimator=gbr,
    param_grid=gbr_params,
    scoring='neg_mean_squared_error',
    cv=5,
    verbose=1,
    n_jobs=-1
)

grid_search.fit(X_train, y_train)

# Best model
best_gbr = grid_search.best_estimator_
print("Best Parameters:", grid_search.best_params_)

# Model evaluation
y_pred_val = best_gbr.predict(X_val)
rmse = np.sqrt(mean_squared_error(y_val, y_pred_val))
print(f"Validation RMSE: {rmse}")

# Predictions on test set
y_pred_test = best_gbr.predict(X_test)

# Transform predictions back to original scale
y_pred_test = np.expm1(y_pred_test)

# Prepare submission
submission = pd.DataFrame({
    'Id': test_ids,
    'SalePrice': y_pred_test
})

# Save submission file
submission.to_csv('submission.csv', index=False)
print("Submission file has been successfully created!")
print(submission)



