# -*- coding: utf-8 -*-
"""Jack He - Natural Language Processing with Disaster Tweets

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fKhejcw2EVDgotY0ukKuBRtvHp6vtU4J
"""

import pandas as pd
import numpy as np
import re
import string
import matplotlib.pyplot as plt
import seaborn as sns

# NLP / ML Libraries
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (
    accuracy_score,
    classification_report,
    confusion_matrix,
    precision_score,
)

# Load datasets
train_path = "train.csv"
test_path = "test.csv"
submission_path = "sample_submission.csv"

train_df = pd.read_csv(train_path)
test_df = pd.read_csv(test_path)
submission_df = pd.read_csv(submission_path)

# Inspect class distribution
print("Train set label distribution:")
print(train_df["target"].value_counts())

plt.figure(figsize=(6,4))
sns.countplot(x="target", data=train_df, palette="viridis")
plt.title("Flood vs. Not Flood Tweets")
plt.xlabel("Target (0 = Not Disaster, 1 = Disaster)")
plt.ylabel("Count")
plt.show()

# Text Cleaning
STOPWORDS = set(stopwords.words("english"))

def clean_text(text: str) -> str:
    text = str(text).lower()
    text = re.sub(f"[{re.escape(string.punctuation)}]", " ", text)
    tokens = text.split()
    tokens = [tok for tok in tokens if tok not in STOPWORDS and tok.isalpha()]
    return " ".join(tokens)

# Apply cleaning
train_df["clean_text"] = train_df["text"].apply(clean_text)
test_df["clean_text"] = test_df["text"].apply(clean_text)

# Vectorization
tfidf = TfidfVectorizer(ngram_range=(1,2), max_features=5000)
X = tfidf.fit_transform(train_df["clean_text"])
X_test = tfidf.transform(test_df["clean_text"])
y = train_df["target"]

# Train/Test Split for validation
X_train, X_val, y_train, y_val = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)
print(f"\nValidation split: Train={X_train.shape[0]}, Val={X_val.shape[0]}")

# Model Training
clf = LogisticRegression(max_iter=1000, n_jobs=-1)
clf.fit(X_train, y_train)

# Evaluation on validation set
y_pred = clf.predict(X_val)
print(f"\nValidation Accuracy: {accuracy_score(y_val, y_pred):.4f}\n")
print("Validation Classification Report:")
print(classification_report(y_val, y_pred, zero_division=0))

# Confusion Matrix
conf_mat = confusion_matrix(y_val, y_pred)
plt.figure(figsize=(5,4))
sns.heatmap(conf_mat, annot=True, fmt="d", cmap="Blues")
plt.title("Validation Confusion Matrix")
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.show()

# Retrain on full training set
clf_full = LogisticRegression(max_iter=1000, n_jobs=-1)
clf_full.fit(X, y)

# Predict on test set and prepare submission
test_preds = clf_full.predict(X_test)
submission_df["target"] = test_preds
submission_out = "submission.csv"
submission_df.to_csv(submission_out, index=False)
print(f"\nSubmission file saved to: {submission_out}")